name: adaptive_navigation_example
description: An example to show how to use the adaptive_navigation_scaffold

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <2.10.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_navigation:
    path: ../
  adaptive_breakpoints:
    path: ../../adaptive_breakpoints/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
