name: adaptive_components
description: Implements Material Adaptive Components.
version: 0.0.1
homepage: https://github.com/material-components/material-components-flutter-adaptive

environment:
  sdk: '>=2.9.0 <2.10.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints:
    path: ../adaptive_breakpoints/
  adaptive_navigation:
    path: ../adaptive_navigation/

dev_dependencies:
  flutter_test:
    sdk: flutter
