name: example
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
